[package]
name = "reverse_proxy_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.4"
rocket = "0.5.0"
tokio = "1.37.0"
